version: "3.7"

services:
  carlemany-backend:
    build:
      context: .
      target: carlemany-backend-base
    image: carlemany-backend-base
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: .
        target: /carlemany-backend
    env_file:
      - .env
    ports:
      - "8000:80"
    networks:
      - carlemany-net

  postgres:
    image: postgres:13.4-alpine3.14
    environment:
      - POSTGRES_DB=${PSQL_DB_DATABASE}
      - POSTGRES_USER=${PSQL_DB_USERNAME}
      - POSTGRES_PASSWORD=${PSQL_DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - type: volume
        source: carlemany-backend-data
        target: /var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${PSQL_DB_USERNAME}
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - carlemany-net

  black:
    image: carlemany-backend-base:latest
    volumes:
      - type: bind
        source: ./
        target: /carlemany-backend
        read_only: true
    entrypoint: sh -c "black --config .black --check --diff ."

  test: &test
    image: carlemany-backend-dev:latest
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./
        target: /carlemany-backend
    networks:
      - carlemany-net
    entrypoint: pytest --maxfail=10

  test-cov:
    <<: *test
    entrypoint: pytest --maxfail=10 --cov --cov-report=term --cov-report=html --junitxml=tests/test-results/junit.xml

volumes:
  carlemany-backend-data:
networks:
  carlemany-net:
